name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.8'  # Specify your PHP version

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build  # Adjust this command based on your project's build script

      - name: Run Tests
        run: |
          phpunit  # Run PHP tests
          npm test  # Run Node.js tests (if any)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/master'
        run: |
          ssh user@your_server_ip "cd /path/to/your/project && git pull origin master && composer install --no-dev && npm install && npm run build && php artisan migrate --force"

      - name: Deploy to Staging Server
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh user@your_staging_server_ip "cd /path/to/your/project && git pull origin staging && composer install --no-dev && npm install && npm run build && php artisan migrate --force"
